### PR TITLE
#2273 When user selects and moves atom on Functional Group or Salt it doesn't replaces atom in the structure

### LINKED ISSUE #2273: When user selects and moves atom on Functional Group or Salt it doesn't replaces atom in the structure
**Steps to Reproduce**
1. Open Ketcher
2. Add Functional Group or Salt to the canvas 
3. Add an atom to the canvas
4. Using selection tool select the atom and move it over FG or Salt

**Actual behavior**
Atom doesn't replace FG or Salt, it displayed on the canvas over the FG or Salt

**Expected behavior**
Atom replaces a FG or Salt

**Screenshots**

https://user-images.githubusercontent.com/124911723/221199332-941b5c81-9d18-4241-99ae-30e545c840d2.mov

**Desktop (please complete the following information):**
 - OS: MacOS 13.2 (22D49)
 - Browser: Chrome
 - Version: Version 110.0.5481.100 (Official Build) (x86_64)

**Ketcher version** [e.g. v2.4.2]. 
[Version 2.8.0-rc.4]

**Additional context**
Related discussion: https://github.com/epam/ketcher/discussions/2315

### PR DESCRIPTION
**Pull request by VasilevDO**
Closes #2273

### CODE REVIEW

**Review by AnastasiiaPlyako — APPROVED** [review]

**Comment by KonstantinEpam23** [comment]
@VasilevDO looks like this breaks the behaviour for adding a bond to a functional group.

Steps to reproduce: place a functional group on the canvas, select bond tool and click on the functional group.
Actual behaviour: Bond is not added to functional group.
Expected: Bond is added to attachment point atom of functional group.

File: packages/ketcher-react/src/script/editor/tool/helper/dropAndMerge.ts [hunk 1]
```diff
@@ -84,39 +84,25 @@ function getExpandGroupsInMergeAction(
...
-          ),
-          bonds: [...SGroup.getBonds(struct, sGroup)]
-        })
-      )
-
-      removeSGroup.mergeWith(fromSgroupDeletion(reStruct, functionalGroupId))
-    }
+    const selectedSgroup = reStruct.sgroups.get(functionalGroupId)
+    const sGroupAtoms = SGroup.getAtoms(reStruct.molecule, selectedSgroup?.item)
+    const [firstAtom, ...atoms] = sGroupAtoms
```
Comment (KonstantinEpam23) [inline packages/ketcher-react/src/script/editor/tool/helper/dropAndMerge.ts:99]: First atom is not guaranteed to be the attachment point, perhaps it is better to keep using `sGroup?.getAttAtomId(struct)` ?
