### PR TITLE
#2215 – When moving mouse cursor over created S-Group pop-up tool tip does not disappear

### LINKED ISSUE #2214: Tooltip appears on the structure immediately without delay
**Steps to Reproduce**
1. Open Ketcher
2. Create structure and make Data S-Group with 'Field name' and 'Field value'
3. With 'Selection tool' hover over created S-Group

**Actual behavior**
Tool tip appears on the structure immediately without delay

Note: Similar behavior is seen in Functional Groups, Salt and Solvents...

**Expected behavior**
More consistent behavior should assume that when the mouse stops on the structure, it causes a pop-up tool tip after a certain period of time

**Screenshots**

https://user-images.githubusercontent.com/62464241/218752377-10f1ce8a-96bb-409f-a495-3dbc9ec10022.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.8.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

### LINKED ISSUE #2215: When moving mouse cursor over created S-Group pop-up tool tip does not disappear
**Steps to Reproduce**
1. Open Ketcher
2. Create structure and make Data S-Group with 'Field name' and 'Field value'
3. With 'Selection tool' hover over created S-Group and move mouse cursor on highlited area

**Actual behavior**
When moving mouse cursor over created S-Group pop-up tool tip does not disappear. 
This does not allow you to see the entire structure and makes it difficult to interact with it.
Note: Similar behavior is seen in Functional Groups, Salt and Solvents...

**Expected behavior**
More consistent behavior should assume that when the mouse cursor moving on highlited area, pop-up tool tip dissapear and when user stop mouse cursor on highlited area it causes a pop-up tool tip after a certain period of time.

**Screenshots**

https://user-images.githubusercontent.com/62464241/218756791-7ade9bef-095d-401e-b562-a8f1117bd4e7.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.8.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

### PR DESCRIPTION
**Pull request by Nitvex**
closes #2215 
closes #2214

### CODE REVIEW

File: packages/ketcher-react/src/script/ui/state/functionalGroups/index.ts [hunk 1]
```diff
@@ -63,7 +63,7 @@ function notDebouncedHighlightFG(dispatch, group: any) {
   dispatch(highlightFGroup(group))
 }
 
-export const highlightFG = _.debounce(notDebouncedHighlightFG, 200)
+export const highlightFG = memoizedDebounce(notDebouncedHighlightFG, 100, [0])
```
Comment (KonstantinEpam23) [inline packages/ketcher-react/src/script/ui/state/functionalGroups/index.ts:66]: I think originally we settled on a 400ms delay, did the requirements change?

**Review by KonstantinEpam23 — APPROVED** [review]

File: packages/ketcher-react/src/script/editor/utils/functionalGroupsTooltip.ts [hunk 2]
```diff
@@ -0,0 +1,38 @@
+import { FunctionalGroup } from 'ketcher-core'
+
+let showTooltipTimer: ReturnType<typeof setTimeout> | null = null
+
+export function showTooltip(editor, infoPanelData) {
+  editor.event.showInfo.dispatch(null)
```
Comment (KonstantinEpam23) [inline packages/ketcher-react/src/script/editor/utils/functionalGroupsTooltip.ts:6]: Why we need to do this?
