### PR TITLE
#2043: Thumbnail images are not readable in Template Dialog

### LINKED ISSUE #2043: Thumbnail images are not readable in Template Dialog
**Steps to Reproduce**
1. Open template dialog
2. Switch to "Functional Groups" tab
3. Observe some large structure

**Actual behavior**
Some structures are not fully readable due to small font size

**Expected behavior**
It is required to increase font size for elements to make structures readable

**Screenshots**
Example of unreadable structure:
image

### PR DESCRIPTION
**Pull request by KonstantinEpam23**
Closes #2043

### CODE REVIEW

**Comment by KonstantinEpam23** [comment]
This is an updated version of: https://github.com/epam/ketcher/pull/2063

File: packages/ketcher-react/src/script/ui/dialog/template/TemplateTable.tsx [hunk 1]
```diff
@@ -71,8 +70,13 @@ const RenderTmpl: FC<{
   return (
     <StructRender
       struct={tmpl.struct}
-      options={{ ...options, autoScaleMargin: 15 }}
       {...props}
+      options={{
+        ...options,
+        autoScaleMargin: 10,
+        cachePrefix: 'templates',
+        downScale: true
```
Comment (epam-nikolai-iakushchenko) [inline packages/ketcher-react/src/script/ui/dialog/template/TemplateTable.tsx:78]: why not name it starting with 'is' so that it's clear it's a boolean?

File: packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx [hunk 2]
```diff
@@ -350,6 +354,7 @@ export default connect(
   (store) => ({
     ...omit(['attach'], (store as any).templates),
     initialTab: (store as any).modal?.prop?.tab || TemplateTabs.TemplateLibrary,
+    renderOptions: (store as any).editor?.render?.options,
```
Comment (epam-nikolai-iakushchenko) [inline packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx:357]: is it possible to add a shape for a store?

Comment (KonstantinEpam23) [reply packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx:357]: Its not that easy unfortunately, kind of scared of breaking other things

File: packages/ketcher-react/src/script/ui/dialog/template/TemplateTable.tsx (hunk 1 above)
Comment (KonstantinEpam23) [reply packages/ketcher-react/src/script/ui/dialog/template/TemplateTable.tsx:78]: This one I did via analogy to "autoScale" property that we already had.

File: packages/ketcher-react/src/script/ui/dialog/template/TemplateTable.tsx [hunk 3]
```diff
@@ -41,9 +40,9 @@ interface TemplateTableProps {
   onDelete?: (tmpl: Template) => void
   onAttach?: (tmpl: Template) => void
   titleRows?: 1 | 2
+  renderOptions?: any
```
[the remark this answers is not in the document]
Comment (KonstantinEpam23) [reply packages/ketcher-react/src/script/ui/dialog/template/TemplateTable.tsx:43]: we don't have one now, I think we can add that as a separate refactor ticket for the future

**Review by Nitvex — APPROVED** [review]
