### PR TITLE
#2009 - Incorrect positioning of data s-group labels

### LINKED ISSUE #2009: Incorrect positioning of data s-group labels
**Steps to Reproduce**
1. Launch Ketcher
2. Create chain structure or Benzene
3. Highlight all structure by Selection tool
4. Click on  'Data S-Group' button
5. In 'S-Group Properties' window select from drop-down menu: 'Context-Atom or Bond', 'Field name-A', 'Field value-2', 'Radio button-Absolute or Relative'
6. Click 'Apply' button
7. Look at structure

**Actual behavior**
Adding to Atom or Bond a Data S-Group the attachment point on the structure is incorrect

**Expected behavior**
Adding to Atom or Bond a Data S-Group the attachment point on the structure is correct: Atom value on atom, Bond value on bond
Mapping for Atoms:
2022-12-27_14h51_44
Mapping for Bonds:
2022-12-27_14h53_31

**Screenshots**
2022-12-27_15h00_11
2022-12-27_15h02_09

https://user-images.githubusercontent.com/62464241/209664896-0f157d93-8b0e-4f75-b1db-744071486849.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.7.0-rc.7](https://lifescience.opensource.epam.com/ketcher/index.html)

### PR DESCRIPTION
**Pull request by gairon**
Closes #2009 
* Fix Box2Abs.segmentIntersection to check colliniar segments those might not intersect
* Draw bond data labels in the middle of the bond over it

### CODE REVIEW

File: packages/ketcher-core/src/application/render/restruct/resgroup.js [hunk 1]
```diff
@@ -343,9 +343,12 @@ function drawAbsoluteDat(restruct, sgroup) {
 
   const ps = sgroup.pp.scaled(options.scale)
   const name = showValue(paper, ps, sgroup, options)
-  const box = util.relBox(name.getBBox())
 
-  name.translateAbs(0.5 * box.width, -0.5 * box.height)
+  if (sgroup.data.context !== 'Bond') {
```
Comment (rrodionov91) [inline packages/ketcher-core/src/application/render/restruct/resgroup.js:347]: I would recommend to create constants for data contexts and use it everywhere instead of string literal

File: packages/ketcher-core/src/domain/entities/sgroup.ts [hunk 2]
```diff
@@ -161,34 +161,33 @@ export class SGroup {
   calculatePP(struct: Struct): void {
     let topLeftPoint
 
-    if (this.data.context === 'Atom' || this.data.context === 'Bond') {
+    const isAtomContext = this.data.context === 'Atom'
+    const isBondContent = this.data.context === 'Bond'
```
Comment (rrodionov91) [inline packages/ketcher-core/src/domain/entities/sgroup.ts:165]: Here too

**Review by rrodionov91 — APPROVED** [review]

File: packages/ketcher-core/src/application/render/restruct/resgroup.js (hunk 1 above)
Comment (gairon) [reply packages/ketcher-core/src/application/render/restruct/resgroup.js]: Fixed

File: packages/ketcher-core/src/domain/entities/sgroup.ts (hunk 2 above)
Comment (gairon) [reply packages/ketcher-core/src/domain/entities/sgroup.ts]: Fixed

**Review by Zhirnoff — APPROVED** [review]

**Review by rrodionov91 — APPROVED** [review]
