### PR TITLE
#2038: Charge Tool Hot key: Pressing the hot button (5) on an atom applies the opposite charge

### LINKED ISSUE #2038: Charge Tool Hot key: Pressing the hot button (5) on an atom applies the opposite charge
**Steps to Reproduce**
1. Launch Ketcher
2. Create structure (e.g. Benzene)
3. Hover mouse over atom and press the "5" hot key
4. Press the "5" hot key outside the atom
5. Hover mouse over atom and press the "5" hot key

**Actual behavior**
Pressing the hot key (5) on an atom applies the opposite charge

**Expected behavior**
Pressing the hot key (5) on an atom applies the currently selected charge at 'Charge Tool'

**Screenshots**

https://user-images.githubusercontent.com/62464241/209972909-512eebc0-c567-4b93-9f2a-5d726855ee23.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.7.0-rc.8](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

### PR DESCRIPTION
**Pull request by St-Permiakov**
Prevent implicit picking next tool in a group when hovering over a shape.
Related to #1826 
Resolves #2038

### CODE REVIEW

File: packages/ketcher-react/src/script/ui/state/hotkeys.ts [hunk 1]
```diff
@@ -63,23 +63,26 @@ function keyHandle(dispatch, state, hotKeys, event) {
...
+      // check if atom is currently hovered over
+      // in this case we do not want to activate the corresponding tool
+      // and just insert the atom directly
       if (isHoveringOverAtom && newAction.tool !== 'select') {
-        // check if atom is currently hovered over
-        // in this case we do not want to activate the corresponding tool
-        // and just insert the atom directly
+        // keep current selected tool if applicable
+        const prevActName = group[index]
+        if (prevActName) newAction = actions[prevActName].action
```
Comment (epam-nikolai-iakushchenko) [inline packages/ketcher-react/src/script/ui/state/hotkeys.ts:85]: Why not move this to util?
This way we don't need a comment, make the code more declarative, can reuse it, and make this huge 50-line handler a little smaller.

Comment (St-Permiakov) [reply packages/ketcher-react/src/script/ui/state/hotkeys.ts]: Extracted to helper function.

**Review by Nitvex — APPROVED** [review]
