### PR TITLE
#1936 Adding functional group to atom generate a JavaScript console error

### LINKED ISSUE #1936: Adding functional group to atom generate a JavaScript console error
**Steps to Reproduce**
1. Launch Ketcher
2. Draw something, e.g. C-C
3. Select the "PO3" functional group
4. Click on one of the carbons
Note: Console errors also generates after switching between tabs 'Template Library', 'Functional Groups', 'Salts ans Solvents'
**Actual behavior**
A JavaScript console error happens.

**Expected behavior**
There are no errors in the console

**Screenshots**
2022-12-15_14h28_57

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Ketcher version** 
[v2.7.0]

### PR DESCRIPTION
**Pull request by ansivgit**
fix #1936
Added handle if template is null

### CODE REVIEW

**Review by KonstantinEpam23 — APPROVED** [review]

File: packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx [hunk 1]
```diff
@@ -330,6 +330,14 @@ const TemplateDialog: FC<Props> = (props) => {
   )
 }
 
+const selectTemplate = (template, props, dispatch) => {
+  dispatch(selectTmpl(null))
+  if (!template) return
```
Comment (Nitvex) [inline packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx:335]: I propose to write conditions with curly brackets, even when they're single line
