### PR TITLE
#2011 Reaction Mapping Tool: Manual mapping of atoms does not work

### LINKED ISSUE #2011: Reaction Mapping Tool: Manual mapping of atoms does not work
**Steps to Reproduce**
1. Launch Ketcher
2. Create two structures on the canvas. (e.g. Benzene)
2. Select any arrow tool.
3. Click on the canvas between structures.
4. Select 'Reaction Mapping Tool'.
5. Map some atoms.

**Actual behavior**
Manual mapping of atoms does not work

**Expected behavior**
Manual mapping of atoms works
2022-12-27_19h37_35

**Screenshots**

https://user-images.githubusercontent.com/62464241/209695108-f9fa4275-fe1b-494f-a273-bda710250934.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.7.0-rc.7](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

### PR DESCRIPTION
**Pull request by ansivgit**
fixed #2011 

- fixed ci that returns null
- remove validation as we needn't it any more because we no longer have restrictions on the direction/numbers of the arrows from the reactant to the product or from node to node of the structure

### CODE REVIEW

File: packages/ketcher-react/src/script/editor/tool/reactionmap.ts [hunk 1]
```diff
@@ -51,11 +51,7 @@ class ReactionMapTool {
       const ci = this.editor.findItem(event, ['atoms'], this.dragCtx.item)
       const atoms = rnd.ctab.molecule.atoms
 
-      if (
-        ci &&
-        ci.map === 'atoms' &&
-        isValidMap(this.rcs, this.dragCtx.item.id, ci.id)
-      ) {
+      if (ci && ci.map === 'atoms') {
```
Comment (epam-nikolai-iakushchenko) [inline packages/ketcher-react/src/script/editor/tool/reactionmap.ts:54]: let's rename `ci` to `closestItem` shall we?
Developers that come after us will be very grateful

File: packages/ketcher-react/src/script/editor/tool/reactionmap.ts [hunk 2]
```diff
@@ -91,13 +87,9 @@ class ReactionMapTool {
...
       const rnd = this.editor.render
-      const ci = this.editor.findItem(event, ['atoms'], this.dragCtx.item)
+      const ci = this.editor.findItem(event, ['atoms'])
 
-      if (
-        ci &&
-        ci.map === 'atoms' &&
-        isValidMap(this.rcs, this.dragCtx.item.id, ci.id)
-      ) {
+      if (ci && ci.map === 'atoms') {
```
Comment (epam-nikolai-iakushchenko) [inline packages/ketcher-react/src/script/editor/tool/reactionmap.ts:92]:
```suggestion
      if (ci?.map === 'atoms') {
```

**Review by Nitvex — APPROVED** [review]
