### PR TITLE
#2548 – If name of Superatom matches abbreviation in Custom Templates, then tooltip is shown on hover

### LINKED ISSUE #2548: If name of Superatom matches abbreviation in Custom Templates, then tooltip is shown on hover
**Steps to Reproduce**
1. Open Ketcher
2. Create Superatom with name 'FMOC' or any other that exist in 'Custom Templates'
3. Hover cursor over created Superatom

**Actual behavior**
If name of Superatom matches abbreviation in Custom Templates, then tooltip is shown on hover

**Expected behavior**
Custom Superatoms do not have a tooltips

**Screenshots**
2023-04-27_19h19_01
2023-04-27_19h19_35

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.10.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

#185047754

### PR DESCRIPTION
**Pull request by Nitvex**
closes #2548
S-Group doesn't contain its underlying struct (needs to be refactored), so as a simple fix I've added construction of `Struct` from its atoms and bonds.

### CODE REVIEW

File: packages/ketcher-react/src/script/editor/utils/functionalGroupsTooltip.ts [hunk 1]
```diff
@@ -1,9 +1,39 @@
...
+  const struct = new Struct()
+  const atomsIdMapping = new Map()
+
+  sGroup.atoms.forEach((atomId) => {
+    const atomIdInTooltip = struct.atoms.add(existingStruct.atoms.get(atomId))
+    atomsIdMapping.set(atomId, atomIdInTooltip)
+  })
+  Array.from(existingStruct.bonds).forEach((value) => {
+    const [_, bond] = value as [number, Bond]
+    const clonedBond = cloneDeep(bond)
```
Comment (KonstantinEpam23) [inline packages/ketcher-react/src/script/editor/utils/functionalGroupsTooltip.ts:19]: Bond has a method .clone() - perhaps we can use that?

**Review by AnastasiiaPlyako — APPROVED** [review]
