### PR TITLE
#2047: Templates: When the structure is pasted or dragged on each other, carbon atoms are highlighted

### LINKED ISSUE #2047: Templates: When the structure is pasted or dragged on each other, carbon atoms are highlighted
**Steps to Reproduce**
1. Launch Ketcher
2. Select 'Benzene' from Templates
3. Paste it on canvas
4. Select 'Benzene' from Templates and paste over 'Benzene'
5. Place two 'Benzene' on the canvas and drag one onto the other

**Actual behavior**
When the structure is pasted or dragged on each other, carbon atoms are wrongly highlighted as "bad valence".

**Expected behavior**
Fully overlapping identical templates using Paste should result in merging without change.
Fully overlapping identical templates using using Dragging-drop should result in merging without change.

**Screenshots**

https://user-images.githubusercontent.com/62464241/210354700-5c1443f5-ffc3-40a7-87f3-cf53cdfa0e21.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.7.0-rc.8](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

### PR DESCRIPTION
**Pull request by St-Permiakov**
Fixes a big issue with valence validation upon merging structures.
Previously validation was performed atom by atom alongside other modifications, which resulted in miscalculations when taking into account atoms that were queued for deletion.
Now it is performed separately, after all merges complete, and takes into account all connected atoms in case structure is changed.

Resolves #2047

### CODE REVIEW

File: packages/ketcher-core/src/application/editor/actions/closelyFusing.ts [hunk 1]
```diff
@@ -98,3 +106,52 @@ function closestToMerge(struct, closestMap) {
 
   return mergeMap
 }
+
+function mergeItemsFuseMap(items: Map<number, number>): Set<number> {
```
Comment (epam-nikolai-iakushchenko) [inline packages/ketcher-core/src/application/editor/actions/closelyFusing.ts:110]: This function name is not clear to me.
Does this function filter out duplicated items?
Then maybe filterOutDuplicatedItems?
Thoughts?

File: packages/ketcher-core/src/application/editor/actions/closelyFusing.ts [hunk 2]
```diff
@@ -98,3 +106,52 @@ function closestToMerge(struct, closestMap) {
...
+  const itemsSet = new Set<number>()
+  items.forEach((value, key) => {
+    itemsSet.add(value).add(key)
+  })
+  return itemsSet
+}
+
+function getAllConnectedAtomsIds(restruct, atomsIds, bondsIds) {
+  const srcAtoms = new Set(atomsIds)
```
Comment (epam-nikolai-iakushchenko) [inline packages/ketcher-core/src/application/editor/actions/closelyFusing.ts:119]: srcAtoms? atoms from the source? 🤔

Comment (St-Permiakov) [reply packages/ketcher-core/src/application/editor/actions/closelyFusing.ts:119]: Source atoms. The atoms we are beginning with. I couldn't come up with a better naming. Any ideas?

File: packages/ketcher-core/src/application/editor/actions/closelyFusing.ts (hunk 1 above)
Comment (St-Permiakov) [reply packages/ketcher-core/src/application/editor/actions/closelyFusing.ts:110]: Well, it merges items into one array. Thus — mergeItems.
I can name it "mergeItemsIntoOneArrayFuseMap" if it helps.
Can't get rid of "FuseMap" part because it's highly niсhe and not supposed to be used anywhere else.

File: packages/ketcher-core/src/application/editor/actions/closelyFusing.ts (hunk 2 above)
Comment (epam-nikolai-iakushchenko) [reply packages/ketcher-core/src/application/editor/actions/closelyFusing.ts:119]: why not just 'atoms'?

File: packages/ketcher-core/src/application/editor/actions/closelyFusing.ts (hunk 1 above)
Comment (epam-nikolai-iakushchenko) [reply packages/ketcher-core/src/application/editor/actions/closelyFusing.ts:110]: can't say 'mergeItemsIntoOneSetFuseMap' looks easier to understand from my point of view 🤔 
Can you please explain what this function does if it doesn't filter out duplicated items?
And why is this 'fuseMap' thing needed? What does it mean?

Comment (St-Permiakov) [reply packages/ketcher-core/src/application/editor/actions/closelyFusing.ts:110]: > Can you please explain what this function does if it doesn't filter out duplicated items?
->
> ...it merges items into one Set.

It sure does remove any duplicated items, but it's not the point of this function.

> And why is this 'fuseMap' thing needed?
->
> ...because it's highly niсhe and not supposed to be used anywhere else.

The wording of this part can be tweaked, just not removed entirely, so the whole sense would not be lost.

File: packages/ketcher-core/src/application/editor/actions/closelyFusing.ts (hunk 2 above)
Comment (St-Permiakov) [reply packages/ketcher-core/src/application/editor/actions/closelyFusing.ts:119]: Because the result of the function is also "atoms". So basically we can name result "atoms" as well and we'll get function making atoms from atoms.
In order to differentiate them in some way we divide them into "source atoms" — the ones we are using for the process — and the resulting "connected atoms", which are the goal of the process.

File: packages/ketcher-core/src/application/editor/actions/closelyFusing.ts (hunk 1 above)
Comment (epam-nikolai-iakushchenko) [reply packages/ketcher-core/src/application/editor/actions/closelyFusing.ts:110]: > It sure does remove any duplicated items, but it's not the point of this function.
> The wording of this part can be tweaked, just not removed entirely, so the whole sense would not be lost.

What is the point of this function then? Sorry, I struggle to grasp the whole sense of this function 🤷

File: packages/ketcher-core/src/application/editor/actions/closelyFusing.ts (hunk 2 above)
Comment (epam-nikolai-iakushchenko) [reply packages/ketcher-core/src/application/editor/actions/closelyFusing.ts:119]: Isn't it 

```
() => {
 const atoms;
 ?
 return  ̶p̶r̶o̶f̶i̶t̶ connectedAtoms
}
```

?

Comment (St-Permiakov) [reply packages/ketcher-core/src/application/editor/actions/closelyFusing.ts:119]: This way we have no clue about the purpose of this variable.
Are those target atoms? Are they going to be modified? Returned? What are we going to do with them?
Defining them as "source atoms" clearly states that it's an input to some process and they are not going to be used in any other way.

Comment (TimSPb89) [reply packages/ketcher-core/src/application/editor/actions/closelyFusing.ts:119]: maybe `initialAtoms` would be more straightforward then, what do you think?

Comment (St-Permiakov) [reply packages/ketcher-core/src/application/editor/actions/closelyFusing.ts:119]: Do not see the difference, but ok, will rename it if this helps.

File: packages/ketcher-core/src/application/editor/actions/closelyFusing.ts (hunk 1 above)
Comment (St-Permiakov) [reply packages/ketcher-core/src/application/editor/actions/closelyFusing.ts]: Clarified in direct messages. 
And renamed a little to make the process more transparent.

**Review by Nitvex — APPROVED** [review]

**Review by KonstantinEpam23 — APPROVED** [review]
