### PR TITLE
#5700 - System allow to establish infinit number of bonds from monomer to microstructure

### LINKED ISSUE #5700: System allow to establish infinit number of bonds from monomer to microstructure
**Steps to Reproduce**
1. Go to Macro - Flex
2. Load from file: [Connection from the center of monomer to micro structure should cause Select Connection Point dialog.zip](https://github.com/user-attachments/files/17293899/Connection.from.the.center.of.monomer.to.micro.structure.should.cause.Select.Connection.Point.dialog.zip)
image
3.  Establish connection by dragging center of monomer to any atom
(system establishes R2 - atom connection)
4. Establish connection by dragging R3 of monomer to any atom

**Actual behavior**
Starting from that moment - by dragging center of monomer to any atom you can establish as much connections as you want
image

**Expected behavior**
Only possible to establish as much connections as monomer have available

**Versions**
- Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
- Indigo Toolkit Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Win10

Issue found while testing: https://github.com/epam/ketcher/issues/5359

### PR DESCRIPTION
**Pull request by lmhs**
## How the feature works? / How did you fix the issue?
Following the proposal by @tanas80 and further discussion with @AlexeyGirin and @ljubica-milovic it was approved that to resolve issue #5700 creation of non-hydrogen bond from center of the CHEM monomer must be forbidden with notification banner displayed if bond target is Atom, only attachment points can be used for creating bonds from CHEM monomer to Atoms

Fixes #5700 

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [x] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

### CODE REVIEW

**Review by NataliaLoginova — APPROVED** [review]

File: packages/ketcher-core/src/application/editor/tools/Bond.ts [hunk 1]
```diff
@@ -465,21 +466,36 @@ class PolymerBond implements BaseTool {
 
     const atomRenderer = event.target.__data__ as AtomRenderer;
     const monomer = this.bondRenderer?.polymerBond.firstMonomer;
+
+    if (
+      monomer instanceof Chem &&
```
Comment (rrodionov91) [inline packages/ketcher-core/src/application/editor/tools/Bond.ts:471]: Please delete ```monomer instanceof Chem &&``` because restriction should work for all types of monomers

File: ketcher-autotests/tests/Macromolecule-editor/Polymer-Bond-Tool/connection-rules-for-chems-monomers.spec.ts [hunk 2]
```diff
@@ -1252,39 +1228,6 @@ test.describe('Connection rules for chems: ', () => {
...
-       *  Description: Verify that connection points between monomers and molecules can be created by drawing bonds in macro mode
-       *  Case: Monomer center to molecule atom connection
-       *  Step: 1. Load monomer (chem) and shift it to the left
-       *        2. Load molecule (system loads it at the center)
-       *        3. Drag center of monomer to first (0th) atom of molecule
-       *        Expected result: No connection should be establiched
-       *  WARNING: That test tesults are wrong because of bug: https://github.com/epam/ketcher/issues/5976
-       *  Screenshots must be updated after fix and fixme should be removed
-       */
-      test(`Case 11: Connect Center of Chem(${leftMonomer.alias}) to atom of MicroMolecule(${rightMolecule.alias})`, async () => {
```
Comment (rrodionov91) [inline ketcher-autotests/tests/Macromolecule-editor/Polymer-Bond-Tool/connection-rules-for-chems-monomers.spec.ts:1268]: If we deleted tests, then please delete screenshots related to it

**Review by rrodionov91 — CHANGES_REQUESTED** [review]

File: packages/ketcher-core/src/application/editor/tools/Bond.ts (hunk 1 above)
Comment (ALexanderSPB) [reply packages/ketcher-core/src/application/editor/tools/Bond.ts:471]: image

Comment (rrodionov91) [reply packages/ketcher-core/src/application/editor/tools/Bond.ts:471]: I saw the description.
I'm 100% sure that it should work for every type of monomer. Discussed with @AlexeyGirin one more time, he approved. Please remove the line.

File: packages/ketcher-core/src/application/editor/tools/Bond.ts [hunk 3]
```diff
@@ -465,21 +466,32 @@ class PolymerBond implements BaseTool {
 
     const atomRenderer = event.target.__data__ as AtomRenderer;
     const monomer = this.bondRenderer?.polymerBond.firstMonomer;
+
+    if (!this.isHydrogenBond && !monomer.chosenFirstAttachmentPointForBond) {
+      this.editor.events.error.dispatch(
+        'CHEM monomer to Atom supports only attachment points for bond creation',
```
Comment (lmhs) [inline packages/ketcher-core/src/application/editor/tools/Bond.ts:472]: if new rule is applied not just for CHEM monomers, then please update this message

Comment (ALexanderSPB) [reply packages/ketcher-core/src/application/editor/tools/Bond.ts]: Updated

File: ketcher-autotests/tests/Macromolecule-editor/Polymer-Bond-Tool/connection-rules-for-chems-monomers.spec.ts (hunk 2 above)
Comment (ALexanderSPB) [reply ketcher-autotests/tests/Macromolecule-editor/Polymer-Bond-Tool/connection-rules-for-chems-monomers.spec.ts:1268]: Deleted

**Review by rrodionov91 — APPROVED** [review]
