### PR TITLE
#9306: Refactor: fixed binary expression should not always return same value issue

### LINKED ISSUE #9306: Refactor: (TypeScript) Binary expressions should not always return the same value
**Problem:** 
Unexpected constant binary expression. Compares constantly with the right-hand side of the `!=`

**Why is this an issue?**
Comparisons that always evaluate to true or to false, logical expressions that either always or never short-circuit and comparisons to a newly constructed object should not be used.

An expression that always produces the same result, regardless of the inputs, is unnecessary and likely indicates a programmer’s error. This can come from

confusing operator precedence
expecting strict equality between different types
expecting objects to be compared by value
expecting empty objects to be false or null
mistyping >= for ⇒
This can also happen when you put an assignment in a logical sub-expression. While not strictly a bug, this practice is confusing and should be avoided.

**How can I fix it?**
Review the code around the issue to find out why the expression always produces the same result. Pay attention to the operator precedence, comparing objects of different types, and comparing objects by reference (not by value!).

**Noncompliant code example**

```
!foo == null;
a + b ?? c;
x === [];
(foo=0) && bar;
```

**Compliant solution**

```
foo != null;
a + (b ?? c);
x.length === 0;
```

**Problem locations:**
packages/ketcher-core/src/application/editor/actions/erase.ts

### PR DESCRIPTION
**Pull request by oguzhanduran**
## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

### CODE REVIEW

File: packages/ketcher-core/src/application/editor/actions/erase.ts [hunk 1]
```diff
@@ -118,7 +118,7 @@ export function fromOneBondDeletion(restruct, id) {
 }
 
 export function fromFragmentDeletion(restruct, rawSelection) {
-  assert(!!rawSelection != null);
+  assert(rawSelection != null);
```
Comment (svvald) [inline packages/ketcher-core/src/application/editor/actions/erase.ts:121]: Maybe we could explore if it's safe to use strict comparison `!==` here for better clarity?

Comment (oguzhanduran) [reply packages/ketcher-core/src/application/editor/actions/erase.ts:121]: The rawSelection parameter has no type annotation, so it could be null or undefined. Using != null guards against both cases, so I think better to leave as it is

**Review by svvald — APPROVED** [review]
