### PR TITLE
#2994 - Attachment points should be within S-Group brackets

### LINKED ISSUE #2994: Attachment points should be within S-Group brackets
Steps to Reproduce

1. Go to Ketcher
2. Create structure with S-Group (Multi Group/SRU Polimer)
3. Add attachment point for the same atom

Actual behaviour
image

Expected behaviour
Attachment points should be inside of S-Group

Ketcher version [e.g. v2.4.2].
Version 2.13.0-rc.2

### PR DESCRIPTION
**Pull request by Nitvex**
## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

closes #2994 
original PR https://github.com/epam/ketcher/pull/3126
[tests run successfully in local while failed in pipeline.docx](https://github.com/epam/ketcher/files/12617586/tests.run.successfully.in.local.while.failed.in.pipeline.docx)
click-and-drag-salts-on-canvas.spec.ts: will need Nikita's fix in another pr: https://github.com/epam/ketcher/pull/3306

## Check list
- [x] unit-tests written
- [x] e2e-tests written
- [x] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [x] task status changed to "Code review"
- [x] reviewers are notified about the pull request

### CODE REVIEW

**Comment by Zhirnoff** [comment]
I guess that for Multiple group the "Repeat count" numbers indication should be positioned on the lower right side of the brackets. Not in the right upper side. The rest of the brackets are also incorrectly displayed. The example on the left is correct
2023-08-31_18h46_13
2023-08-31_18h55_25
2023-08-31_19h02_20
2023-08-31_19h07_04

File: packages/ketcher-core/src/application/render/draw.ts [hunk 1]
```diff
@@ -1365,20 +1365,27 @@ function radicalBullet(
...
-  const a1 = c.addScaled(n, 0.5 * bracketHeight);
-  const b0 = a0.addScaled(d, -bracketWidth);
-  const b1 = a1.addScaled(d, -bracketWidth);
+  let a0, a1;
+  if (isBracketContainAttachment) {
+    a0 = bondCenter.addScaled(bracketDirection, 0.2 * bracketHeight);
+    a1 = bondCenter.addScaled(bracketDirection, -0.8 * bracketHeight);
+  } else {
+    a0 = bondCenter.addScaled(bracketDirection, -0.5 * bracketHeight);
+    a1 = bondCenter.addScaled(bracketDirection, 0.5 * bracketHeight);
```
Comment (rrodionov91) [inline packages/ketcher-core/src/application/render/draw.ts:1385]: is it possible to name these magic numbers somehow? And also it would be great to rename a0/a1/... to something more meaningful.

File: packages/ketcher-core/src/application/render/restruct/resgroup.ts [hunk 2]
```diff
@@ -249,62 +249,111 @@ function SGroupdrawBrackets({
...
     );
     set.push(path);
     if (
       ir < 0 ||
-      brackets[ir].d.x < bracket.d.x ||
-      (brackets[ir].d.x === bracket.d.x && brackets[ir].d.y > bracket.d.y)
+      brackets[ir].bracketAngleDirection.x < bracket.bracketAngleDirection.x ||
+      (brackets[ir].bracketAngleDirection.x ===
+        bracket.bracketAngleDirection.x &&
+        brackets[ir].bracketAngleDirection.y > bracket.bracketAngleDirection.y)
```
Comment (rrodionov91) [inline packages/ketcher-core/src/application/render/restruct/resgroup.ts:296]: Could you please rename "ir" if you know what is it?

File: packages/ketcher-core/src/application/render/restruct/resgroup.ts [hunk 3]
```diff
@@ -398,103 +447,164 @@ function drawAttachedDat(restruct: ReStruct, sgroup: SGroup): any {
...
+            tr,
+            util.shiftRayBox(rightCenter, rightDirection, boundingBox),
+          );
+          tt = Math.max(
+            tt,
+            util.shiftRayBox(cc, bracketDirection, boundingBox),
+          );
+          tb = Math.max(
+            tb,
+            util.shiftRayBox(cc, bracketDirectionNegated, boundingBox),
```
Comment (rrodionov91) [inline packages/ketcher-core/src/application/render/restruct/resgroup.ts:528]: Could you please rename tl/tr/tt/... ?

File: packages/ketcher-core/src/application/render/restruct/resgroup.ts [hunk 4]
```diff
@@ -398,103 +447,164 @@ function drawAttachedDat(restruct: ReStruct, sgroup: SGroup): any {
...
+          leftCenter,
+          direction.negated(),
+          bracketWidth,
+          bracketHeight,
+        ),
+        new BracketParams(rightCenter, direction, bracketWidth, bracketHeight),
       );
     })();
   } else if (crossBondsValues.length === 2 && crossBondsPerAtom.length === 2) {
     (function () {
```
Comment (rrodionov91) [inline packages/ketcher-core/src/application/render/restruct/resgroup.ts:492]: Why this code in if else statements is wrapper to IIFE?

**Review by rrodionov91 — CHANGES_REQUESTED** [review]

**Review by rrodionov91 — CHANGES_REQUESTED** [review]

**Review by rrodionov91 — CHANGES_REQUESTED** [review]
Could you please check this scenario? I think it is a bug.
https://github.com/epam/ketcher/assets/14859362/b4ff41d1-65bc-428a-b5cb-410a2a27fcb3

**Review by rrodionov91 — APPROVED** [review]
