### PR TITLE
#1894 – added support for extra spaces and alias in mol v2000 files

### LINKED ISSUE #1894: Add support for extra spaces and quotes in alias for mol v2000 files
# Problem
At the moment, parsing mol file, which has more than 3 spaces between 'A' and atom number and an alias, which contains quotes, results in an error:

image

# Expected behaviour
It is required to add a possibility to parse mol files, which contain extra spaces and quotes in aliases. So parsing example mol file:

```

  MJ211800                      

  7  5  0  0  0  0  0  0  0  0999 V2000
   11.7937   -2.6391    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.7937   -3.4427    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.7937   -5.0553    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.4921   -4.6522    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.4921   -3.8459    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.1879   -5.0540    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   14.7955   -7.0478    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  3  4  1  0  0  0  0
  4  5  2  0  0  0  0
  5  2  1  0  0  0  0
  4  6  1  0  0  0  0
A    7
'Assumed'
M  END
```
Shall be successful and structure should be able to be added on a canvas:

image

### PR DESCRIPTION
**Pull request by Nitvex**
When Atom has alias with single quotes, it is parsed as "pseudo". This "pseudo" didn't have corresponding setter, that's why error was shown.
resolves #1894

### CODE REVIEW

**Review by epam-nikolai-iakushchenko — APPROVED** [review]

File: packages/ketcher-core/src/domain/serializers/mol/common.js [hunk 1]
```diff
@@ -43,10 +43,13 @@ function parseCTab(/* string */ ctabLines) /* Struct */ {
...
   ctabLines = ctabLines.slice(1)
-  if (version === 'V2000') return v2000.parseCTabV2000(ctabLines, countsSplit)
-  else if (version === 'V3000') {
+  if (version === 'V2000') {
+    return v2000.parseCTabV2000(ctabLines, countsSplit)
+  } else if (version === 'V3000') {
     return v3000.parseCTabV3000(ctabLines, !loadRGroupFragments)
-  } else throw new Error('Molfile version unknown: ' + version) // eslint-disable-line no-else-return
+  } else {
+    throw new Error('Molfile version unknown: ' + version) // eslint-disable-line no-else-return
```
Comment (epam-nikolai-iakushchenko) [inline packages/ketcher-core/src/domain/serializers/mol/common.js:51]: I think we can get rid of else on lines 48 and 50
This way we won't need an eslint exception

**Review by KonstantinEpam23 — APPROVED** [review]

File: packages/ketcher-core/src/domain/serializers/mol/common.js (hunk 1 above)
Comment (Nitvex) [reply packages/ketcher-core/src/domain/serializers/mol/common.js]: Good proposal, thanks
