### PR TITLE
Macro: #3633 – undo/redo does not toggle snake mode

### LINKED ISSUE #3633: Macro: undo/redo does not toggle snake mode
**Steps to Reproduce**
1. Go to Macromolecules mode
2. Add peptide chain on canvas
3. Click on 'Snake mode' button on left tool panel
4. Click on 'Undo' button on left tool panel

**Actual behavior**
Chain position changed on previous one(before snake layout), however snake mode still turned on and bonds drawn as snake ones.

**Expected behavior**
Snake mode turned off and bonds drawn as straight lines.

### PR DESCRIPTION
**Pull request by Nitvex**
## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

closes #3633

## Check list
- [ ] unit-tests written
- [x] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [x] task status changed to "Code review"
- [x] reviewers are notified about the pull request

### CODE REVIEW

File: packages/ketcher-core/src/application/editor/Editor.ts [hunk 1]
```diff
@@ -127,14 +127,17 @@ export class CoreEditor {
 
   // todo we need to create abstraction layer for modes in future similar to the tools layer
```
Comment (rrodionov91) [inline packages/ketcher-core/src/application/editor/Editor.ts:128]: I believe we can remove this comment because you created such layer

**Review by rrodionov91 — APPROVED** [review]

**Review by StarlaStarla — APPROVED** [review]

**Review by rrodionov91 — APPROVED** [review]
