### PR TITLE
#2294 After replace tooltip from a previously 'Functional Groups' or 'Salts and Solvents' is displayed on hover

### LINKED ISSUE #2294: After replace tooltip from a previously 'Functional Groups' or 'Salts and Solvents' is displayed on hover
**Steps to Reproduce**
1. Open Ketcher
2. Add to canvas 'Functional Groups' or 'Salts and Solvents'
3. Select any 'Functional Groups'
4. Click on 'Functional Groups' or 'Salts and Solvents' on canvas
5. Hover cursor over abbreviation

**Actual behavior**
After replace tooltip from a previously 'Functional Groups' or 'Salts and Solvents' is displayed on hover

**Expected behavior**
Tooltip should display an image corresponding to its abbreviation

**Screenshots**

https://user-images.githubusercontent.com/62464241/222482166-d1e397f3-94e9-4794-bde9-aa7fd531b614.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.8.0-rc.5](https://lifescience.opensource.epam.com/ketcher/index.html)

**Test case**
[EPMLSOPKET-10106] 
[EPMLSOPKET-10107]

**Additional context**

### PR DESCRIPTION
**Pull request by KonstantinEpam23**
Closes #2294

### CODE REVIEW

File: packages/ketcher-react/src/script/editor/tool/template.ts [hunk 1]
```diff
@@ -428,19 +430,20 @@ class TemplateTool {
...
-          atoms: [...SGroup.getAtoms(struct, closestGroup)].filter(
-            (atomId) => atomId !== attachmentAtomId
-          ),
-          bonds: [...SGroup.getBonds(struct, closestGroup)]
-        })
+      const restruct = this.editor.render.ctab
+      const functionalGroupToReplace = struct.sgroups.get(ci.id)!
+      const attachmentAtomId = functionalGroupToReplace.getAttAtomId(struct)
+      const sGroupAtoms = SGroup.getAtoms(struct, functionalGroupToReplace)
+      const [_, ...atoms] = sGroupAtoms
```
Comment (yuleicul) [inline packages/ketcher-react/src/script/editor/tool/template.ts:439]: Hi, if I understand correctly, `atoms` is an array of all the S-Group atoms except for the attachment atom.
So my question is, why the first atom of `sGroupAtoms` is the attachment atom? Is it a convention?

**Review by Nitvex — APPROVED** [review]
