### PR TITLE
#6090- Antisense creating doesn't work if ambiguous phosphate present in the chain selection

### LINKED ISSUE #6090: Antisense creating doesn't work if ambiguous phosphate present in the chain selection
Note: Probably https://github.com/epam/ketcher/issues/6090, https://github.com/epam/ketcher/issues/6091 and https://github.com/epam/ketcher/issues/6092 has the same root cause 

**Steps to Reproduce**
1. Go to Macro - Snake mode
2. Load from HELM using paste from clipboard: `RNA1{R(A)([gly],[hn])}$$$$V2.0`
image
3. Select all monomers on the canvas and click Create Antisense Strand from context menu

**Actual behavior**
Nothing happens
Error in console:
image

**Expected behavior**
Antisense chain created. Phosphate in anti-sence chain should be natural `P`
image

As per [requirement](https://github.com/epam/ketcher/issues/5678):

> 1.3. If multiple chains are selected and more than one satisfies the previous requirements, the "Create Antisense Strand" option should appear, and if clicked, multiple antisense chains are created.

> 2.2. Every nucleotide (sugar and phosphate are part of the backbone and connected via R2(s)-R1(p), and the sugar is connected to a "sense base" via R3(s)-R1(b)) should transform into a nucleotide on the antisense chain that contains ribose (R), phosphate (P), and the appropriate "antisense base".

**Versions**
- Ketcher Version 2.28.0-rc.1 Build at 2024-12-03; 17:04:52
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.109 (Official Build) (64-bit)
- Win10

Issue found while testing - https://github.com/epam/ketcher/issues/5678

### PR DESCRIPTION
**Pull request by beyzaevcen**
## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

 Summary
- Fixes a crash when "Create Antisense Strand" is used on a chain
  containing an ambiguous monomer (e.g. `RNA1{R(A)([gly],[hn])}`)
- Root cause: `AmbiguousMonomer.monomerItem` lacks the `monomers` array,
  causing `undefined.map()` in the constructor when copied naively
- Fix: ambiguous monomers in the backbone are replaced with natural
  phosphate (P) in the antisense chain, matching the expected behavior
  per requirement 2.2

 Changes
- `createAntisenseChain`: detect `AmbiguousMonomer` in backbone else-branch
  and substitute with natural phosphate P instead of copying
- `addMonomer` / `addMonomerChangeModel`: broadened signature from
  `MonomerItemType` to `MonomerOrAmbiguousType` to support the fallback

Now It looks like this:
Screenshot 2026-04-07 at 13 45 21

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

### CODE REVIEW

File: packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts [hunk 1]
```diff
@@ -3681,12 +3681,17 @@ export class DrawingEntitiesManager {
...
+            const antisenseMonomerItem =
+              isModifiedPhosphate || isAmbiguousMonomer
+                ? getRnaPartLibraryItem(
+                    editor,
+                    RNA_DNA_NON_MODIFIED_PART.PHOSPHATE,
+                  ) ??
+                  (isAmbiguousMonomer
+                    ? monomer.variantMonomerItem
+                    : monomer.monomerItem)
+                : monomer.monomerItem;
```
Comment (svvald) [inline packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts]: Seem to be good from the functional standpoint, however, I'd try to improve readability here and avoid using nested ternary operators, could you please fix it?

**Review by svvald — CHANGES_REQUESTED** [review]

**Review by svvald — APPROVED** [review]
