### PR TITLE
#2482 – Ketcher with iFrame loads with scrollbars activated

### LINKED ISSUE #2482: Ketcher with iFrame loads with scrollbars activated
**Steps to Reproduce**
1. Go to Ketcher with iFrame
2. Click 'Open Modal'
3. Wait for Ketcher window to load and look at canvas

**Actual behavior**
Ketcher with iFrame loads with scrollbars activated
2023-04-13_14h40_57

**Expected behavior**
Ketcher with iFrame loads without scrollbars activated

2023-04-13_14h42_23

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.9.0-rc.6]

### PR DESCRIPTION
**Pull request by Nitvex**
closes #2482

### CODE REVIEW

File: packages/ketcher-react/src/script/ui/component/form/input.tsx [hunk 1]
```diff
@@ -60,7 +60,7 @@ export function GenericInput({
     <>
       <input
         type={type}
-        value={value}
+        value={value ?? ''}
```
Comment (KonstantinEpam23) [inline packages/ketcher-react/src/script/ui/component/form/input.tsx:63]: 👍

**Review by KonstantinEpam23 — APPROVED** [review]
