### PR TITLE
#2389 - Bracket is missing when opening a file RXN v2000/v3000 files with 'S-Group Properties Type = Multiple group'

### LINKED ISSUE #2389: Bracket is missing when opening a file RXN v2000/v3000 files with 'S-Group Properties Type = Multiple group'
**Steps to Reproduce**

**Scenario1**
1. Launch Ketcher
2. Open RXN v2000 file with 'S-Group Properties Type = Multiple group [Multi.zip](https://github.com/epam/ketcher/files/11001722/Multi.zip)

**Actual behavior**
Pop-up message:
WARNING!
Unsupported S-group type found. Would you like to import structure without it? And file opens without one of S-Group bracket.
2023-03-17_16h20_26
2023-03-17_16h09_46

**Expected behavior**
File opens without pop-up message. With all added S-Group Properties and brackets on its places
2023-03-17_16h08_28

**Scenario2**
1. Launch Ketcher
2. Open RXN v3000 file with 'S-Group Properties Type = Multiple group [rxnV3000Multiple.zip](https://github.com/epam/ketcher/files/11001809/rxnV3000Multiple.zip)

Actual and Expected results same as for RXN v2000

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.9.0-rc.3](https://lifescience.opensource.epam.com/ketcher/index.html)

**Test case**
[EPMLSOPKET-1903]

### PR DESCRIPTION
**Pull request by vitaepam**
## How the feature works? / How did you fix the issue?
- 'DAT' S-Groups did not implement function which draw brackets for such type of groups
- replaced packages/ketcher-core/src/application/render/restruct/resgroup.js with TypeScript 
- optimised some parts of resgroup.ts
- added folder and first e2e test for S-Group structures

(Screenshots, videos, or GIFs, if applicable)
Closes #2389 

## Check list
- [ ] unit-tests written
- [x] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [x] task status changed to "Code review"

### CODE REVIEW

File: packages/ketcher-core/src/domain/entities/sgroup.ts [hunk 1]
```diff
@@ -82,6 +82,9 @@ export class SGroup {
   neiAtoms: any;
   pp: Vec2 | null;
   data: any;
+  dataArea: any;
+  atomId?: number;
```
Comment (Nitvex) [inline packages/ketcher-core/src/domain/entities/sgroup.ts:86]: What `atomId` do you mean?
What is `position`?

File: packages/ketcher-core/src/application/render/restruct/resgroup.ts [hunk 2]
```diff
@@ -14,25 +14,50 @@
...
+import { RenderOptions } from '../render.types';
+interface SGroupdrawBracketsOptions {
+  set: any;
+  render: Render;
+  sgroup: SGroup;
+  crossBonds: { [key: number]: Array<Bond> };
+  atomSet: Pile;
+  bracketBox: Box2Abs;
+  d: Vec2;
+  lowerIndexText?: string | null;
```
Comment (Nitvex) [inline packages/ketcher-core/src/application/render/restruct/resgroup.ts:45]: What do you mean here by `index`?

File: packages/ketcher-core/src/application/render/restruct/resgroup.ts [hunk 3]
```diff
@@ -349,55 +370,53 @@ function drawAbsoluteDat(restruct, sgroup) {
...
 function getBracketParameters(
-  mol,
-  crossBonds,
-  atomSet,
-  bracketBox,
-  d,
-  render,
-  id,
-) {
+  mol: any,
```
Comment (Nitvex) [inline packages/ketcher-core/src/application/render/restruct/resgroup.ts:400]: Most likely, type of mol is `Struct`

File: packages/ketcher-core/src/domain/entities/sgroup.ts (hunk 1 above)
Comment (vitaepam) [reply packages/ketcher-core/src/domain/entities/sgroup.ts]: You are right, I don't need this, these variables would be received as a result of getContractedPosition()
Removed

File: packages/ketcher-core/src/application/render/restruct/resgroup.ts (hunk 2 above)
Comment (vitaepam) [reply packages/ketcher-core/src/application/render/restruct/resgroup.ts:46]: Index here as far as I understood from code and S-Groups behaviour is this 
Screenshot 2023-08-14 at 20 42 34

File: ketcher-autotests/tests/Templates/S-Groups/s-groups.spec.ts [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+
+  // this test works locally, but do not work in CI for some reason
+  test.fixme(
+    'Open file with several s-groups and check brackets',
+    async ({ page }) => {
+      /*
+    Test case related to issue: https://github.com/epam/ketcher/issues/2389
+    Description: Open file with S-groups (with Unsupported S-group type) and see that brackets in place for all S-Groups except DAT
+    */
+      await waitForLoad(page, async () => {
```
Comment (Nitvex) [inline ketcher-autotests/tests/Templates/S-Groups/s-groups.spec.ts:27]: You don't need `waitForLoad` here. That's because `openFileAndAddToCanvas` already invokes that function

Comment (vitaepam) [reply ketcher-autotests/tests/Templates/S-Groups/s-groups.spec.ts]: Updated

**Comment by vitaepam** [comment]
I run all tests that fail in CI locally and most of them pass (screenshots attached).
erase-tool.spec.ts - need to be reviewed and fixed, it has some strange issue. Added for now fixme()
Screenshot 2023-08-17 at 16 05 53
Screenshot 2023-08-17 at 16 08 42
Screenshot 2023-08-17 at 16 18 27
Screenshot 2023-08-17 at 16 21 12
Screenshot 2023-08-17 at 16 33 38
Screenshot 2023-08-17 at 16 38 11
Screenshot 2023-08-18 at 10 34 00
Screenshot 2023-08-18 at 10 35 47
Screenshot 2023-08-18 at 10 37 48
Screenshot 2023-08-18 at 10 39 47

**Review by Nitvex — APPROVED** [review]

**Comment by Zhirnoff** [comment]
Tested. Bug is not fixed.

https://github.com/epam/ketcher/assets/62464241/83856192-8c59-4156-a45f-f60ec0c50956

File: ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/Erase-Tool/erase-tool.spec.ts [hunk 5]
```diff
@@ -16,6 +19,7 @@ function checkElementExists(element: RxnPlus | RxnArrow, errorMsg: string) {
 let point: { x: number; y: number };
 
 test.describe('Erase Tool', () => {
+  // TO DO: here in both tests we have some issue with openFileAndAddToCanvas() function it need proper investigation
```
Comment (Zhirnoff) [inline ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/Erase-Tool/erase-tool.spec.ts:22]: What is the problem in the 'openFileAndAddToCanvas()' function?

**Comment by Zhirnoff** [comment]
Pre-tested.
2023-08-30_12h01_18

**Review by Zhirnoff — APPROVED** [review]
