### PR TITLE
#2033: Abbreviations: Atoms protrude beyond the expanded view

### LINKED ISSUE #2033: Abbreviations: Atoms protrude beyond the expanded view for Functional Groups and Salts and Solvents
**Steps to Reproduce**
1. Launch Ketcher
2. Press 'Custom Templates' button and click on 'Functional Groups' tab
3. Select for example 'CO2tBu' and add to canvas
4. Press 'Custom Templates' button and click on 'Salts and Solvents' tab
5. Select for example 'methane sulphonic acid' and add to canvas
6. Expand the abbreviations and look at appeared images

**Actual behavior**
Expand abbreviation for Functional Groups and Salts and Solvents works incorrectly - atoms protrude beyond the expanded view

**Expected behavior**
Expand abbreviation for Functional Groups and Salts and Solvents works correctly - atoms not protrude beyond the expanded view. The whole structure fits into an expand square.

**Screenshots**
2022-12-29_14h51_14

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.7.0-rc.8](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

### PR DESCRIPTION
**Pull request by TimSPb89**
This PR resolves #2033 #899:
Abbreviations: Atoms protrude beyond the expanded view for Functional Groups and Salts and Solvents

### CODE REVIEW

File: packages/ketcher-core/src/domain/entities/sgroup.ts [hunk 1]
```diff
@@ -331,7 +331,9 @@ export class SGroup {
   static bracketPos(
     sGroup,
     mol,
-    crossBondsPerAtom: { [key: number]: Array<Bond> }
+    crossBondsPerAtom: { [key: number]: Array<Bond> },
+    remol?,
```
Comment (KonstantinEpam23) [inline packages/ketcher-core/src/domain/entities/sgroup.ts:335]: What is "remol"? Maybe lets add a type here?

File: packages/ketcher-core/src/domain/entities/sgroup.ts [hunk 2]
```diff
@@ -348,12 +350,24 @@ export class SGroup {
...
+      return mol.atoms.get(aid)
+    }
     atoms.forEach((aid) => {
-      const atom = mol.atoms.get(aid)
-      const pos = new Vec2(atom.pp)
+      const atom = getAtom(aid)
       const ext = new Vec2(0.05 * 3, 0.05 * 3)
-      const bba = new Box2Abs(pos, pos).extend(ext, ext)
-      contentBoxes.push(bba)
+      let pos
```
Comment (KonstantinEpam23) [inline packages/ketcher-core/src/domain/entities/sgroup.ts:362]: maybe lets name these "position" and "structBoundingBox" ?

File: packages/ketcher-core/src/domain/entities/sgroup.ts [hunk 3]
```diff
@@ -348,12 +350,24 @@ export class SGroup {
...
+      let bba
```
Comment (KonstantinEpam23) [inline packages/ketcher-core/src/domain/entities/sgroup.ts:363]: maybe lets name these "position" and "structBoundingBox" ?

Comment (TimSPb89) [reply packages/ketcher-core/src/domain/entities/sgroup.ts]: done

File: packages/ketcher-core/src/domain/entities/sgroup.ts (hunk 1 above)
Comment (TimSPb89) [reply packages/ketcher-core/src/domain/entities/sgroup.ts]: Added typing

File: packages/ketcher-core/src/domain/entities/sgroup.ts [hunk 4]
```diff
@@ -348,12 +351,24 @@ export class SGroup {
...
     atoms.forEach((aid) => {
-      const atom = mol.atoms.get(aid)
-      const pos = new Vec2(atom.pp)
+      const atom = getAtom(aid)
       const ext = new Vec2(0.05 * 3, 0.05 * 3)
-      const bba = new Box2Abs(pos, pos).extend(ext, ext)
-      contentBoxes.push(bba)
+      let position
+      let structBoundingBox
+      if ('getVBoxObj' in atom && render) {
```
Comment (KonstantinEpam23) [inline packages/ketcher-core/src/domain/entities/sgroup.ts:365]: Hmm, why is this check for 'getVBoxObj' needed?

Comment (TimSPb89) [reply packages/ketcher-core/src/domain/entities/sgroup.ts]: replaced with `instanceof` check

**Comment by KonstantinEpam23** [comment]
This also closes #899

**Review by ansivgit — APPROVED** [review]

**Review by KonstantinEpam23 — APPROVED** [review]
