### PR TITLE
#4405 - Macro: Switching to Sequence mode causes page freeze

### LINKED ISSUE #4568: Preview: Pasted sequences are not visible in the Snake mode.
**Steps to Reproduce**

1. Switch to Macro >> Snake mode
2. Open file 
[ketcher (8).zip](https://github.com/epam/ketcher/files/15187711/ketcher.8.zip)
3. Select all >> Copy
image

3. Go to Sequence mode 
image

4. Paste
image

5. Go to Snake mode  again
image

6. Try to Paste in the Snake mode

**Actual behavior**
Sequences inserted in Snake mode do not appear in Snake mode.
Sequences inserted in Sequence mode are not displayed in Snake and Flex modes. (see first video file)
If you insert sequences into Snake Mode after Flex Mode > Snake Mode becomes empty. (see second video file)

**Expected behavior**
Pasting sequences to the any mode should be visible in the Snake/Flex mode.

https://github.com/epam/ketcher/assets/161723514/686e5fe5-6fb5-427b-be42-522b0a7a8404

https://github.com/epam/ketcher/assets/161723514/b53c1673-6790-40f4-9057-8bbef1c5352a

**Versions:**
[Version 2.21.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)
    Build at 2024-04-29; 09:29:15

Indigo Toolkit
    Version 1.20.0-rc.1.0-g8e8ffc3c3-x86_64-linux-gnu-11.2.1

### PR DESCRIPTION
**Pull request by rrodionov91**
## How the feature works? / How did you fix the issue?
- refactored snake layout to work with ChainsCollection
- also fixes #4568 

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [x] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

### CODE REVIEW

File: packages/ketcher-core/src/domain/entities/monomer-chains/ChainsCollection.ts [hunk 1]
```diff
@@ -49,7 +90,7 @@ export class ChainsCollection {
     firstMonomersInCycledChains.forEach((monomer) => {
       chainsCollection.add(new Chain(monomer, !!IsChainCycled.CYCLED));
     });
-
+    console.log(chainsCollection);
```
Comment (ilya-asiyuk-epam) [inline packages/ketcher-core/src/domain/entities/monomer-chains/ChainsCollection.ts:93]: Forgot to remove it?

**Review by ilya-asiyuk-epam — APPROVED** [review]
