### PR TITLE
#2257 - Unable add a bond to a Function Group

### LINKED ISSUE #2257: Unable to add a bond to a Functional Group by Bond Tool
**Steps to Reproduce**
1. Open Ketcher
2. Add any Functional Group on canvas
3. Select 'Single Bond'
4. Attach to Functional Group
Note: also reproduce with 'Chain'

**Actual behavior**
Unable add a bond to a Function Group

**Expected behavior**
Able add a bond to a Function Group

**Screenshots**

https://user-images.githubusercontent.com/62464241/220338351-8f14035d-ac62-48af-881f-cfff0e189a96.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.8.0-rc.3](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**
Related issue: https://github.com/epam/ketcher/issues/2229

### PR DESCRIPTION
**Pull request by St-Permiakov**
- Add ability to add bond to a contracted group
- Add ability to add chain to a contracted group
 Resolves #2257

### CODE REVIEW

File: packages/ketcher-core/src/application/editor/actions/bond.ts [hunk 1]
```diff
@@ -81,7 +80,8 @@ export function fromBondAddition(
     begin.fragment = frid
     begin = (action.addOp(new AtomAdd(begin, pos).perform(restruct)) as AtomAdd)
       .data.aid
-    if (typeof end === 'number') mergeSgroups(action, restruct, [begin], end)
+    if (typeof end === 'number')
+      mergeFragmentsIfNeeded(action, restruct, begin, end)
```
Comment (KonstantinEpam23) [inline packages/ketcher-core/src/application/editor/actions/bond.ts:84]: Need to add brackets

**Review by KonstantinEpam23 — APPROVED** [review]
