### PR TITLE
#2276 Click & drag an 'Atom' on FG, Salts and Solvents, FG connected with Atom forms many atoms

### LINKED ISSUE #2276: Click & drag an 'Atom' on FG, Salts and Solvents, FG connected with bond issues
**Steps to Reproduce**
1. Open Ketcher
2. Add any Functional Group, Salts and Solvent, Functional Group connected with bond
3. Select any Atom and click & drag on each added element

**Actual behavior**

For FG: many atoms appear 
For Salt and Solvents: many atoms appear
For FG connected with bond: replace

**Expected behavior**

For FG: Connection 'Atom---FG'
For Salt and Solvents: Atom appears where the left mouse button was released without a connection
For FG connected with bond: Connection 'Atom---FG---*'
where '*' - Atom or FG
**Screenshots**

https://user-images.githubusercontent.com/62464241/221222037-a1521749-0746-476a-ad3a-b7458521609f.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.8.0-rc.4](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

### PR DESCRIPTION
**Pull request by VasilevDO**
Closes #2276 
Changes:
1) Atom tool "click and drag" action works as expected now
2) If the user clicks and drags an atom out of the original target, and then hovers back over the original target, the bond action will revert (after the 'mouseup' event, it will trigger a replace action)

### CODE REVIEW

**Comment by yuleicul** [comment]
Hi @VasilevDO , it looks really cool to me in the sense that the bond action will revert after hovering back! 👍 

Unfortunately, I found a small problem which seems not to behave correctly, according to 
> **Expected behavior**
> ...
> For Salt and Solvents: Atom appears where the left mouse button was **released without a connection**
> ...

code-review-2276

**Review by yuleicul — CHANGES_REQUESTED** [review]
Hi @VasilevDO , it looks really cool to me in the sense that the bond-adding action will be reverted after hovering back! 👍 

Unfortunately, I found a small problem which seems not to behave correctly, according to 
> **Expected behavior**
> ...
> For Salt and Solvents: Atom appears where the left mouse button was **released without a connection**
> ...

code-review-2276

File: packages/ketcher-react/src/script/editor/tool/atom.ts [hunk 1]
```diff
@@ -65,174 +65,199 @@ class AtomTool {
...
-            : fromAtomAddition(rnd.ctab, rnd.page2obj(event), this.atomProps))
+    if (!dragCtx.item && !ci) {
+      action.mergeWith(
+        fromAtomAddition(reStruct, rnd.page2obj(event), atomProps)
       )
+    } else if (dragCtx.item && ci) {
+      if (dragCtx.item.id === ci.id) {
+        if (
+          ci.map === 'functionalGroups' &&
+          FunctionalGroup.isContractedFunctionalGroup(ci.id, functionalGroups)
```
Comment (AnastasiiaPlyako) [inline packages/ketcher-react/src/script/editor/tool/atom.ts:214]: that's fun that I have the same logic in my PR  :) I think we need to extract this into a separate function and reuse it. 
https://github.com/epam/ketcher/pull/2580/files#diff-ee62e3d2a7eb8e9230e2d13e3cfe44e4ea9ea805a61f971355d38aab66dda856R62

File: packages/ketcher-react/src/script/editor/tool/atom.ts [hunk 2]
```diff
@@ -65,174 +65,199 @@ class AtomTool {
...
     }
-    if (!ci) {
-      // ci.type == 'Canvas'
-      this.dragCtx = {}
-    } else if (ci.map === 'atoms') {
-      this.dragCtx = { item: ci }
+
+    const ciFunctionalGroupName =
+      ci?.map === 'functionalGroups'
+        ? molecule.functionalGroups.get(ci?.id)?.name
```
Comment (AnastasiiaPlyako) [inline packages/ketcher-react/src/script/editor/tool/atom.ts:102]: could we write here "ci?.map === 'functionalGroups' && molecule.functionalGroups.get(ci?.id)?.name"?

**Comment by yuleicul** [comment]
Just a kind reminder, please remember to click 're-request review' after your code is ready again 😃

**Review by yuleicul — APPROVED** [review]
