### PR TITLE
[Macro]:  #3489 - Preview for monomer does not disappear and prevents you from selecting menu in RNA Builder

### LINKED ISSUE #3489: Macro: Preview for monomer does not disappear and prevents you from selecting menu in RNA Builder
**Steps to Reproduce**
1. Go to Macromolecules mode
2. Click RNA tab
3. Click on 'Sugar' in RNA Builder
4. Select any Sugar

**Actual behavior**
Preview for monomer does not disappear and prevents you from selecting menu in RNA Builder

**Expected behavior**
Preview for monomer disappears and allow you selecting menu in RNA Builder

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/0df2bf8e-427c-4743-a241-3e6fb19fdac5

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.15.0-rc.4](https://lifescience.opensource.epam.com/ketcher/index.html)
Macromolecule ver. 0.1.0

### PR DESCRIPTION
**Pull request by kavalapka**
fixes #3489 

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [x] task status changed to "Code review"
- [x] reviewers are notified about the pull request

### CODE REVIEW

File: packages/ketcher-polymer-editor-react/src/Editor.tsx [hunk 1]
```diff
@@ -162,11 +162,6 @@ function Editor({ theme }: EditorProps) {
 
   const handleOpenPreview = useCallback(
     (e) => {
-      const tools = ['erase', 'select-rectangle', 'bond-single'];
```
Comment (SashaGraves) [inline packages/ketcher-polymer-editor-react/src/Editor.tsx:165]: Are you sure that this should be removed? There is nothing about this logic in initial task

**Review by SashaGraves — APPROVED** [review]

File: packages/ketcher-polymer-editor-react/src/Editor.tsx (hunk 1 above)
Comment (kavalapka) [reply packages/ketcher-polymer-editor-react/src/Editor.tsx]: I have removed it from PR. Thank you.

**Review by rrodionov91 — APPROVED** [review]
