### PR TITLE
#2340 Sliders changed to checkboxes in 'Settings'

### LINKED ISSUE #2340: Sliders changed to checkboxes in 'Settings'
**Steps to Reproduce**
1. Open Ketcher
2. Press 'Settings'
3. Look at sliders

**Actual behavior**
Checkboxes in 'Settings'
Note: in all menu tabs
**Expected behavior**
Sliders in 'Settings'

**Screenshots**
2023-03-13_21h44_08
2023-03-13_21h44_55

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.9.0-rc.3](https://lifescience.opensource.epam.com/ketcher/index.html)

### PR DESCRIPTION
**Pull request by VasilevDO**
Closes #2340

### CODE REVIEW

File: packages/ketcher-react/src/script/ui/component/form/input.tsx [hunk 1]
```diff
@@ -314,6 +314,11 @@ function ctrlMap(component, props: Props) {
 
 function componentMap(props: Props) {
   const { schema, type, multiple } = props
+
+  if (schema?.type === 'boolean' && schema?.description === 'slider') {
```
Comment (gairon) [inline packages/ketcher-react/src/script/ui/component/form/input.tsx:318]: Could you please add tests for this function to make sure that this problem will not return later?

**Review by Nitvex — APPROVED** [review]
