### PR TITLE
Macro: #3498 - When switching from the Macromolecules module to the Molecules module an application crashes

### LINKED ISSUE #3498: Macro: When switching from the Macromolecules module to the Molecules module an application crashes
**Steps to Reproduce**
1.	Launch "Ketcher" and go to the Macromolecules module
2.	Open the Console
3.	Inside the "RNA" section in the "Sugars" subsection, select any sugar
4.	Inside the "RNA" section in the "Bases" subsection, select any base
5.	Inside the "RNA" section in the "Phosphates" subsection, select any phosphate
6.	In the "RNA Builder" subsection, click on the "Add to Presets" button
7.	In the "Presets" subsection, click on this added preset
8.	Click on any empty place on the canvas
9.	Go to the Molecules module

**Actual behavior**
When switching from the Macromolecules module to the Molecules module an application crashes

**Expected behavior**
Switching from the Macromolecules module to the Molecules module should not crash application

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/e08d96fd-c79a-492a-93b9-fc4416957a0e

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (117.0.5938.152) x64

**Ketcher version** 0.1.0

### PR DESCRIPTION
**Pull request by rrodionov91**
Closes #3498 

## How the feature works? / How did you fix the issue?
Added handling the cae when monomer doesn't have specific attachment point but we added bond to it.

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [x] task status changed to "Code review"
- [x] reviewers are notified about the pull request

### CODE REVIEW

**Review by Nitvex — APPROVED** [review]

File: packages/ketcher-core/src/application/editor/Editor.ts [hunk 1]
```diff
@@ -270,12 +270,18 @@ export class CoreEditor {
...
-    );
+    const { conversionErrorMessage } =
+      MacromoleculesConverter.convertDrawingEntitiesToStruct(
+        this.drawingEntitiesManager,
+        struct,
+        reStruct,
+      );
     reStruct.render.setMolecule(struct);
+    if (conversionErrorMessage) {
+      global.ketcher.editor.setMacromoleculeConvertionError(
```
Comment (Nitvex) [inline packages/ketcher-core/src/application/editor/Editor.ts:281]: I propose to use KetcherProvider here instead of `global`

Comment (rrodionov91) [reply packages/ketcher-core/src/application/editor/Editor.ts]: Done
