### PR TITLE
#9709 – It is not correct to have 5' indicator on an antisense chain.

### LINKED ISSUE #9709: It is not correct to have 5' indicator on an antisense chain.
**Steps to Reproduce**
1. Open MacroMolecules mode (clean canvas)
2. Open KET file 

[ExampleForN.zip](https://github.com/user-attachments/files/26606507/ExampleForN.zip)

3, Flex mode >> we can see only 5 indicator for both chains  - **Incorrect**

Image

4. Snake mode >>  We have 3' indicator for antisense chains - **Correct**

Image

**Actual behavior**
We have 5' indicator on an antisense chain in the Flex mode.

**Expected behavior**
It is not correct to have 5' indicator on an antisense chain.
We should only have 3' indicator for antisense chains as in the Snake mode
Snake/flex switching shouldn't change anything.

**Environment details:**
	• [Version 3.15.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html) Build at 2026-04-02; 15:41:30
	• [Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/) Version 1.43.0-rc.1.0-gd74653443-wasm32-wasm-clang-19.0.0
	• Chrome Version 144.0.7559.112 (Official Build) (64-bit)
	• Win11

### PR DESCRIPTION
**Pull request by DmirtyUsov**
## How the feature works? / How did you fix the issue?
**Why Sequence → Flex works but Snake → Flex doesn't**
When leaving Sequence mode: `SequenceMode.initialize()` explicitly calls: `editor.drawingEntitiesManager.recalculateAntisenseChains(!this.isEditMode)`

When leaving Snake mode:` FlexMode.initialize()` calls ONLY` applyFlexLayoutMode(true)` — no` recalculateAntisenseChains`. It relies entirely on the `isAntisense `flags being either correctly restored by undo, or preserved from the snake initialization.

**Fixed**.
Now when entering Flex mode, `recalculateAntisenseChains()` runs first (before `applyFlexLayoutMode` re-adds monomers to the renderer), ensuring `isAntisense/isSense` flags are correctly set based on actual bond connectivity — not on whatever state they were left in after a Snake mode session.
Screenshot 2026-04-15 175936

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [x] task status changed to "Code review"
- [x] reviewers are notified about the pull request
fix #9709

### CODE REVIEW

File: packages/ketcher-core/src/application/editor/modes/FlexMode.ts [hunk 1]
```diff
@@ -14,6 +14,10 @@ export class FlexMode extends BaseMode {
     const command = super.initialize();
     const editor = CoreEditor.provideEditorInstance();
 
+    const antisenseChanges =
+      editor.drawingEntitiesManager.recalculateAntisenseChains();
+    editor.renderersContainer.update(antisenseChanges);
```
Comment (AlexeyGirin) [inline packages/ketcher-core/src/application/editor/modes/FlexMode.ts]: Merge antisenseChanges and modelChanges in row 26 and update them at row 26

Comment (DmirtyUsov) [reply packages/ketcher-core/src/application/editor/modes/FlexMode.ts]: Fixed.

**Review by svvald — APPROVED** [review]
