### PR TITLE
#2266: Atom click on Functional Groups/Salts and Solvents doesn't replace them it forms a scattering of atoms

### LINKED ISSUE #2266: Atom click on Functional Groups/Salts and Solvents doesn't replace them it forms a scattering of atoms
**Steps to Reproduce**
1. Open Ketcher
2. Add Functional Groups/Salts and Solvents on canvas
3. Select atom (e.g. N) and click on Functional Groups/Salts and Solvents

**Actual behavior**
When an atom clicks on a Functional Groups and a Salts and Solvents, instead of replacing it, it forms a scattering of atoms

**Expected behavior**
Atom click on Functional Groups/Salts and Solvents replace them

**Screenshots**

https://user-images.githubusercontent.com/62464241/220941868-9065659a-8121-44b4-b57e-76d485655600.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.8.0-rc.4](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**
Worked in version [Version 2.8.0-rc.3]

https://user-images.githubusercontent.com/62464241/220941898-4a5c5e3a-31a5-4575-a574-98836c4a1173.mp4

### PR DESCRIPTION
**Pull request by KonstantinEpam23**
Closes #2266

### CODE REVIEW

**Review by yuleicul — APPROVED** [review]

File: packages/ketcher-core/src/application/editor/actions/erase.ts [hunk 1]
```diff
@@ -106,16 +102,6 @@ export function fromFragmentDeletion(restruct, selection) {
...
-  restruct.molecule.sgroups.forEach((sg, id) => {
-    if (
-      selection.sgroupData.includes(id) ||
-      new Pile(selection.atoms).isSuperset(new Pile(sg.atoms))
-    ) {
-      actionRemoveDataSGroups.mergeWith(fromSgroupDeletion(restruct, id))
-    }
-  })
-
   selection.atoms.forEach((aid) => {
```
Comment (KonstantinEpam23) [inline packages/ketcher-core/src/application/editor/actions/erase.ts:105]: Removal of data s-group should be taken care of by "removeSgroupIfNeeded" function that is called later: https://github.com/epam/ketcher/pull/2283/files#diff-4830423edc7e30690751de9bd936f4f65337856de30e83de31a0adcf650ddce6L148
