### PR TITLE
#2803 – When user moves mouse, there is a constant update in the '3D Viewer' window

### LINKED ISSUE #2803: When user moves mouse, there is a constant update in the '3D Viewer' window
**Steps to Reproduce**
**Scenario 1**
1. Open Ketcher
2. Press '3D Viewer' button

**Scenario 2**
1. Open Ketcher
2. Add Benzene ring on canvas
3. Press '3D Viewer' button
4. Try rotate structure in 3D Viewer

**Actual behavior**
When user moves mouse, there is a constant update in the '3D Viewer' window. The window update indicator appears.
The structure can't be spinned around all axes.

**Expected behavior**
3D window is open. When moving the mouse, the update indicator does not appear.
3D window is opened. Benzene is drawn in it. The structure can be spinned around all axes.

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/b893edcc-30f7-49af-af99-b20b376ed384

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.12.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

### LINKED ISSUE #2809: Preview for saving structure scrolling back to its original position
**Steps to Reproduce**
1. Open Ketcher
2. Add to canvas any structures
3. Press 'Save' button
4. Try scroll Preview for saving to down

**Actual behavior**
Preview for saving structure scrolling back to its original position

**Expected behavior**
Preview for saving structure not scrolling back to its original position. User can scroll through all file.

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/d3d2cf53-20d6-49e9-8d5d-b6a573c5b3c8

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.12.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

### PR DESCRIPTION
**Pull request by Nitvex**
closes #2803 
closes #2809 

Moved reference type variables to upper scope to prevent unnececessary rerenders
In addition, added selectors for components, which rerendered due to variables with referenced type

### CODE REVIEW

File: packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbar.container.ts [hunk 1]
```diff
@@ -22,6 +22,37 @@ import { onAction } from '../../../state'
...
+const hiddenButtonsSelector = createSelector([getActionState], (actionState) =>
+  Object.keys(actionState).reduce((acc: string[], item) => {
+    if (actionState[item]?.hidden) {
+      acc.push(item)
+    }
+    return acc
+  }, [])
+)
+
+const disableableButtons = [
```
Comment (AnastasiiaPlyako) [inline packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbar.container.ts:48]: Could you fix typo? :)

**Review by AnastasiiaPlyako — APPROVED** [review]
