### PR TITLE
#1906 drawing bonds in one direction does not change the bond created in the other direction

### LINKED ISSUE #1906: Drawing bonds in one direction does not change the bond created in the other direction
**Steps to Reproduce**
1. Create two atoms
2. Link the first atom with the second with a single bond
3. Link the second atom with the first with a double bond

**Actual behavior**
Ketcher displays a triple bond

**Expected behavior**
The second bond replaces the first bond, so result must be double bond (in provided example)

**Screenshots**
Two atoms attached with a single bond:
image
Then, linking from NH2 to H3C results in:
image

**Ketcher version** [e.g. v2.4.2]. 
2.6.4

### PR DESCRIPTION
**Pull request by Nitvex**
closes #1906

### CODE REVIEW

File: packages/ketcher-react/src/script/editor/tool/bond.ts [hunk 1]
```diff
@@ -246,9 +252,16 @@ class BondTool {
             beginPos,
             endPos
           )[0]
+          if (existingBondId) {
+            this.dragCtx.existedBond = bond
```
Comment (KonstantinEpam23) [inline packages/ketcher-react/src/script/editor/tool/bond.ts:256]: existedBond -> existingBond ?

**Review by KonstantinEpam23 — APPROVED** [review]
