### PR TITLE
#2145 – Atom properties is applied to the entire selected structure

### LINKED ISSUE #2145: Atom properties is applied to the entire selected structure
**Steps to Reproduce**
1. Open Ketcher
2. Create structure or open from file [Structure1.zip](https://github.com/epam/ketcher/files/10538819/Structure1.zip)
3. Select whole structure and click on the Carbon atom
4. At 'Atom Properties' window open 'Query specific' menu
5. At 'Substitution count' select 'As drawn' and press 'Apply'
6. Look at structure

**Actual behavior**
Applied the properties of the atom that was double clicked on to all of the atoms in the whole selected structure and 'Nitrogen' atom becomes 'Carbon'.

**Expected behavior**
Only the properties that were changed in the dialog box to be applied, and everything else left unmodified.
If a property is different for some atoms, then display "" (empty string) and do not change it after press Apply
If property is the same for all atoms, then display the value. See examples

**Examples**

* Example 1

Draw and select structure "C=N", 
select all atoms and click atom properties

Label should be equal "" (wrong label validation should not be displayed) 
After applying the changes - structure is kept the same

* Example 2

Draw and select structure "C=C", 
select all atoms and click atom properties

Label should be equal "C"

* Example 3

Draw and select structure "[CH+]=C", 
select all atoms and click atom properties

Label should be equal "C"
Charge should be equal ""

If change charge to 0, and press apply, then the output structure should be C=C

**Screenshots**

https://user-images.githubusercontent.com/62464241/215565667-f5f5c42b-8996-4036-ba32-cfee7dddfad5.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.7.0-rc.10](https://lifescience.opensource.epam.com/ketcher/index.html)

### LINKED ISSUE #2159: Incorrect atom label for selected atom
**Steps to Reproduce**
1. Paste structure "C=N"
2. Select only N atom (by selection tool)
3. Right click on N and press "Edit selected atoms..."

**Actual behavior**
Label is "C"

**Expected behavior**
Label should be "N" since only N was selected

**Desktop (please complete the following information):**
 - OS: Win
 - Chrome

**Ketcher version** 
2.8.0-rc.2

### PR DESCRIPTION
**Pull request by Nitvex**
closes #2145 
closes #2159

### CODE REVIEW

File: packages/ketcher-react/src/script/editor/tool/select.ts [hunk 1]
```diff
@@ -641,6 +633,20 @@ function isSelected(selection, item) {
...
 }
 
+export function getSelectedAtoms(selection, molecule) {
+  if (selection?.atoms) {
+    return mapAtomIdsToAtoms(selection?.atoms, molecule)
+  }
+  return []
+}
+
+export function mapAtomIdsToAtoms(atomsIds: number[], molecule): Atom[] {
```
Comment (KonstantinEpam23) [inline packages/ketcher-react/src/script/editor/tool/select.ts:643]: It seems to return `atomOrReAtom` but the return type is just for `Atom`?

**Review by KonstantinEpam23 — APPROVED** [review]
