### PR TITLE
#2051: S-groups are not interactive when cursor is outside of the hover area

### LINKED ISSUE #2051: S-groups are not interactive when cursor is outside of the hover area
**Steps to Reproduce**
1. Open the template dialog
2. Select "Salts and Solvents" tab
3. Select an item with a long text e.g. "methane sulphonic acid"
4. Add it to the canvas and hover over it with the cursor

**Actual behavior**
The selection does not appear unless you hover near the center of the text

**Expected behavior**
The selection should appear if you hover over the text

**Ketcher version** [e.g. v2.4.2]. 
v2.7.0-rc.8

### PR DESCRIPTION
**Pull request by KonstantinEpam23**
Closes #2051

### CODE REVIEW

**Review by epam-nikolai-iakushchenko — APPROVED** [review]

File: packages/ketcher-react/src/script/editor/shared/closest.js [hunk 1]
```diff
@@ -111,6 +111,16 @@ function findClosestSimpleObject(restruct, pos) {
   return ret
 }
 
+function rectangleContainsPoint(startX, startY, width, height, x, y) {
+  return (
+    startX <= x && x <= startX + width && startY <= y && y <= startY + height
+  )
+}
+
+function distanceBetweenPoints(x1, y1, x2, y2) {
```
Comment (Nitvex) [inline packages/ketcher-react/src/script/editor/shared/closest.js:120]: I believe this functionality is already implemented in `Vec2` class

**Review by Nitvex — APPROVED** [review]
